"""initial schema

Revision ID: 629fbd12094d
Revises: 
Create Date: 2026-06-12 01:21:36.251156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629fbd12094d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('percentile_25', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('percentile_50', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('percentile_75', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry', 'metric_name', name='uq_benchmark_industry_metric')
    )
    op.create_index('ix_benchmark_industry', 'industry_benchmarks', ['industry'], unique=False)
    op.create_index(op.f('ix_industry_benchmarks_id'), 'industry_benchmarks', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("plan IN ('free','pro','enterprise')", name='ck_org_plan'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('language_preference', sa.String(length=20), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("industry IN ('manufacturing','retail','services','agriculture','logistics','e-commerce')", name='ck_company_industry'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gst_number', 'org_id', name='uq_company_gst_org'),
    sa.UniqueConstraint('name', 'org_id', name='uq_company_name_org')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index('ix_companies_industry', 'companies', ['industry'], unique=False)
    op.create_index('ix_companies_org_id', 'companies', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('owner','admin','member')", name='ck_user_role'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_org_id', 'users', ['org_id'], unique=False)
    op.create_table('financial_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('overall_health_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('liquidity_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('profitability_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('leverage_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('credit_risk_level', sa.String(length=10), nullable=True),
    sa.Column('financial_risks', sa.JSON(), nullable=True),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True),
    sa.Column('cost_optimization_suggestions', sa.JSON(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("credit_risk_level IN ('MINIMAL','LOW','MEDIUM','HIGH')", name='ck_assessment_risk_level'),
    sa.CheckConstraint('leverage_score >= 0 AND leverage_score <= 100', name='ck_score_leverage'),
    sa.CheckConstraint('liquidity_score >= 0 AND liquidity_score <= 100', name='ck_score_liquidity'),
    sa.CheckConstraint('overall_health_score >= 0 AND overall_health_score <= 100', name='ck_score_overall'),
    sa.CheckConstraint('profitability_score >= 0 AND profitability_score <= 100', name='ck_score_profitability'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fa_company_date', 'financial_assessments', ['company_id', 'assessment_date'], unique=False)
    op.create_index(op.f('ix_financial_assessments_id'), 'financial_assessments', ['id'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('inventory', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('accounts_receivable', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('accounts_payable', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_statements_id'), 'financial_statements', ['id'], unique=False)
    op.create_index('ix_fs_company_period', 'financial_statements', ['company_id', 'period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fs_company_period', table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_id'), table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index(op.f('ix_financial_assessments_id'), table_name='financial_assessments')
    op.drop_index('ix_fa_company_date', table_name='financial_assessments')
    op.drop_table('financial_assessments')
    op.drop_index('ix_users_org_id', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_companies_org_id', table_name='companies')
    op.drop_index('ix_companies_industry', table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_industry_benchmarks_id'), table_name='industry_benchmarks')
    op.drop_index('ix_benchmark_industry', table_name='industry_benchmarks')
    op.drop_table('industry_benchmarks')
    # ### end Alembic commands ###
